### ISSUE TITLE
Library demands excessive permissions on Linux

### ISSUE THREAD

**Issue by rootabeta** [audreyreal/NSDotPy#12]
Launching a program that uses nsdotpy throws an error message that the program needs to be run as root to intercept keypresses. While this is more of an issue with the keyboard library that nsdotpy relies on, root permissions are unnecessary and dangerous to hand out willy-nilly to every script that might use nsdotpy; therefore this is unacceptable behavior. 

Suggested fix: Consider offering an alternative input method that the author can opt to use when the Session is initialized. https://pypi.org/project/pynput/ seems worth looking into. 

Error trace: 
```╰─$ python3 brimstone.py 
Your main nation: Volstrostia
10:05:55 AM Initialized. Keybind to continue is space.
10:05:55 AM Logging in to alex_asteorra
Traceback (most recent call last):
  File "/home/rootabeta/Projects/Brimstone/brimstone.py", line 8, in <module>
    if session.login(nation, password):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/nsdotpy/session.py", line 632, in login
    response = self.request(url, data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/nsdotpy/session.py", line 344, in request
    response = self._html_request(url, data, files, follow_redirects)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/nsdotpy/session.py", line 274, in _html_request
    userclick = self._wait_for_input(self.keybind)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/nsdotpy/session.py", line 213, in _wait_for_input
    keyboard.wait(key)
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/__init__.py", line 881, in wait
    remove = add_hotkey(hotkey, lambda: lock.set(), suppress=suppress, trigger_on_release=trigger_on_release)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/rootabeta/Projects/Brimstone/lib/python3.11/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```

**Comment by audreyreal** [comment]
i'll push an update when im not fucked up to have it use ``pynput``'s ``xorg`` backend by default on linux, and if it fails because you're on wayland it'll just tell you to run as root; i honestly wasn't aware that pynput had a feature to use ``xorg``, silly me for not reading the documentation thoroughly
